# Generated by Django 4.0.3 on 2022-04-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # migrations.CreateModel(
        #     name='ITBoard',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('Title', models.CharField(max_length=50, verbose_name='제목')),
        #         ('Teaser', models.TextField(verbose_name='내용')),
        #         ('AccID', models.CharField(max_length=15, verbose_name='작성자')),
        #     ],
        # ),
    ]
