# Generated by Django 4.0.3 on 2022-04-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('TeaserID', models.IntegerField(primary_key=True, serialize=False, verbose_name='번호')),
                ('Title', models.CharField(max_length=50, verbose_name='제목')),
                ('Category', models.CharField(max_length=15)),
                ('AccID', models.CharField(max_length=15, verbose_name='작성자')),
                ('Date', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('Clicked', models.IntegerField(verbose_name='조회수')),
            ],
            options={
                'db_table': 'brainTeaser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BoardContents',
            fields=[
                ('TeaserID', models.IntegerField(primary_key=True, serialize=False, verbose_name='번호')),
                ('Title', models.CharField(max_length=50, verbose_name='제목')),
                ('Teaser', models.TextField(verbose_name='본문')),
                ('AccID', models.CharField(max_length=15, verbose_name='작성자')),
                ('Date', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('Clicked', models.IntegerField(verbose_name='조회수')),
            ],
            options={
                'db_table': 'brainTeaser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeaserAnswer',
            fields=[
                ('AnswerID', models.IntegerField(primary_key=True, serialize=False, verbose_name='번호')),
                ('AccID', models.CharField(max_length=15, verbose_name='작성자')),
                ('Answer', models.CharField(max_length=100, verbose_name='댓글')),
                ('Date', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('TeaserID', models.IntegerField(verbose_name='번호')),
                ('Likes', models.IntegerField(verbose_name='좋아요')),
            ],
            options={
                'db_table': 'final_Likes',
            },
        ),
        migrations.DeleteModel(
            name='ITBoard',
        ),
    ]
