# Generated by Django 4.0.4 on 2022-05-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('TeaserID', models.IntegerField(primary_key=True, serialize=False, verbose_name='번호')),
                ('Title', models.CharField(max_length=50, verbose_name='제목')),
                ('Category', models.CharField(max_length=15)),
                ('AccID', models.CharField(max_length=15, verbose_name='작성자')),
                ('Date', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('Clicked', models.IntegerField(verbose_name='조회수')),
            ],
            options={
                'db_table': 'brainTeaser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('PostID', models.IntegerField(primary_key=True, serialize=False, verbose_name='번호')),
                ('Title', models.CharField(max_length=50, verbose_name='제목')),
                ('Category', models.CharField(max_length=15)),
                ('AccID', models.CharField(max_length=15, verbose_name='작성자')),
                ('Date', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('Clicked', models.IntegerField(verbose_name='조회수')),
            ],
            options={
                'db_table': 'community',
                'managed': False,
            },
        ),
    ]
